FROM amazon/aws-cli

#ENV AWS_DEFAULT_REGION='[your region]'
ENV AWS_ACCESS_KEY_ID='AKIA2CD6BD9A0C8EC26C'
ENV AWS_SECRET_ACCESS_KEY='b/i6oHBTOy5OYui+85vvSo9J4jVJuMlor6rargAG'
 
#RUN aws --version 

CMD [ "--version" ]
CMD s3 ls
#ENTRYPOINT [ "aws" ]
#ENTRYPOINT ["tail", "-f", "/dev/null"]

